name: Create Repository
description: 'Creates a new private repository'

inputs:
  repository:
    description: "Name of the repository to be created"
    required: true

outputs:
  created:
    description: "Whether the repository was created"
    value: ${{ steps.creating-repository.outputs.created == 'true' }}

runs:
  using: composite
  steps:
  - name: Check if repository exists
    id: check-repo
    shell: bash
    run: |
      if gh repo view ${{ github.repository_owner }}/${{ inputs.repository }} --json name -q .name > /dev/null 2>&1; then
        echo "Repository already exists."
        echo "exists=true"  >> $GITHUB_OUTPUT
      else
        echo "Repository does not exist."
        echo "exists=false" >> $GITHUB_OUTPUT
      fi

  - name: Create new repository using GitHub CLI
    id: creating-repository
    if: ${{ steps.check-repo.outputs.exists == 'false' }}
    shell: bash
    run: |
      echo "Creating new repository: ${{ inputs.repository }}"
      if gh repo create ${{ github.repository_owner }}/${{ inputs.repository }} --private; then
        echo "created=true" >> $GITHUB_OUTPUT
      else
        echo "created=false" >> $GITHUB_OUTPUT
      fi

  - name: Seed repository with README on master
    if: ${{ steps.creating-repository.outputs.created == 'true' }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    shell: bash
    run: |
      set -e
      workdir="$(mktemp -d)"
      git config --global user.name "${{ github.actor }}"
      git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      git -c init.defaultBranch=master init "$workdir"
      cd "$workdir"
      printf "# %s\n\nRepositório criado automaticamente.\n" "${{ inputs.repository }}" > README.md
      git add README.md
      git commit -m "chore: add README"
      git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository_owner }}/${{ inputs.repository }}.git"
      git push -u origin master
      rm -rf "$workdir"

  - name: Set default branch to master
    if: ${{ steps.creating-repository.outputs.created == 'true' }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    shell: bash
    run: |
      gh repo edit ${{ github.repository_owner }}/${{ inputs.repository }} --default-branch master || true

