name: Create Repository
description: 'Creates a new private repository'

inputs:
  repository:
    description: "Name of the repository to be created"
    required: true

runs:
  using: composite
  steps:
  - name: Check if repository exists
    id: check-repo
    shell: bash
    run: |
      if gh repo view ${{ github.repository_owner }}/${{ inputs.repository }} --json name -q .name > /dev/null 2>&1; then
        echo "Repository already exists."
        echo "exists=true"  >> $GITHUB_OUTPUT
      else
        echo "Repository does not exist."
        echo "exists=false" >> $GITHUB_OUTPUT
      fi

  - name: Create new repository using GitHub CLI
    id: creating-repository
    if: ${{ steps.check-repo.outputs.exists == 'false' }}
    shell: bash
    run: |
      if gh repo create ${{ github.repository_owner }}/${{ inputs.repository }} --private; then
        echo "created=true" >> $GITHUB_OUTPUT
      else
        echo "created=false" >> $GITHUB_OUTPUT
      fi

