name: Create Repository
description: Creates a new GitHub repository

inputs:
  repository:
    description: Repository name to create
    required: true

outputs:
  created:
    description: Repository created successfully
    value: ${{ steps.create.outputs.created }}

runs:
  using: composite
  steps:
    - name: Create repository
      id: create
      shell: bash
      run: |
        gh repo create "${{ inputs.repository }}" --private -y
        echo "created=true" >> $GITHUB_OUTPUT