name: Create Repository
description: 'Creates a new private repository with a master default branch and a README file.'

inputs:
  repository:
    description: "Name of the repository to be created"
    required: true
  pat_token:
    description: "Secret token with permissions to create repositories"
    required: true

runs:
  using: composite
  steps:
    - name: 'Log repository name'
      shell: bash
      run: echo "Creating repository ${{ inputs.repository }}..."

    - name: 'Create new repository using GitHub CLI'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.pat_token }}
        REPO_NAME: ${{ inputs.repository }}
      run: |
        gh repo create $REPO_NAME --private --with-readme --default-branch master
        echo "Repository created successfully!"
        echo "Access it at: https://github.com/${{ github.repository_owner }}/$REPO_NAME"

    - name: 'Output repository URL'
      shell: bash
      run: echo "Repository URL: https://github.com/${{ github.repository_owner }}/${{ inputs.repository }}"