name: Create Repository
inputs:
  language:
    description: 'Programming language of the repository'
    required: true
  repository:
    description: 'Name of the repository to be created'
    required: true
  pat_token:
    description: 'Secret token with permissions to create repositories'
    required: true

runs:
  using: composite
  steps:
    - name: Set up GH CLI authentication
      shell: bash
      run: gh auth login --with-token <<< "${{ inputs.pat_token }}"

    - name: Create repo on GitHub
      shell: bash
      run: |
        gh repo create "${{ github.repository_owner }}/${{ inputs.repository }}" \
          --private --description "Protobuf sources for ${{ inputs.language }}" --confirm

    - name: Clone the new repository
      shell: bash
      run: |
        git clone "https://github.com/${{ github.repository_owner }}/${{ inputs.repository }}.git" new-repo
        cd new-repo

        # Generate README
        echo "# ${{ inputs.repository }}" > README.md
        echo "" >> README.md
        echo "Repositório contendo arquivos \`.proto\` de ${{ inputs.language }}." >> README.md

        # Generate .gitignore
        cat <<'EOF' > .gitignore
        .idea
        .vscode
        node_modules/
        target
        dist
        build
        out
        proto-stubs
        **/.terraform
        **/.terraform.*
        EOF

        # Initial commit & push
        git add README.md .gitignore
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git commit -m "chore: initial commit with README"
        git push origin HEAD:master