name: Release

on:
  workflow_dispatch:

  push:
    paths:
      - 'internal/**'
    branches:
      - master

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  loading-files:
    name: Loading files
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.loading-last-tag.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Next Tag Version
        id: loading-last-tag
        run: |
          git fetch --tags
          LAST_TAG=$(git tag --sort=-v:refname | head -n 1)

          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi

          VERSION=${LAST_TAG#v}
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="v${MAJOR}.${MINOR}.${NEW_PATCH}"

          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "Nova versão: ${NEW_VERSION}"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: loading-files
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create and Push Tag
      run: |
        git tag "v${{ needs.loading-files.outputs.version }}"
        git push --tags

