name: Release

on:
  workflow_dispatch:

  push:
    paths:
      - 'src/**'
    branches:
      - master

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write


jobs:

  loading-files:
    name: Loading files
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.load-version.outputs.version }}
      tag_exists: ${{ steps.extract_version.outputs.tag_exists }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Load POM Version
      id: load-version
      uses: Giustech/actions/.github/actions/loading-pom-version@main

    - name: Use the version no mesmo job
      run: |
        echo "Version: ${{ steps.load-version.outputs.version }}"
        

    - name: Extract version from pom.xml
      id: extract_version
      run: |       
        # Ensure tags are fetched and check remote for the exact tag
        git fetch --tags --prune
        if git ls-remote --tags origin "refs/tags/v${{ steps.load-version.outputs.version }}" | grep -q .; then
          TAG_EXISTS=true
        else
          TAG_EXISTS=false
        fi
        
        echo "new_version=v${{ steps.load-version.outputs.version }}" >> $GITHUB_OUTPUT
        echo "tag_exists=${TAG_EXISTS}" >> $GITHUB_OUTPUT
        echo "Detected version: ${{ steps.load-version.outputs.version }}, tag_exists=${TAG_EXISTS}"


  release:
    runs-on: ubuntu-latest
    name: Generate Release
    needs: loading-files
    if: ${{ needs.loading-files.outputs.tag_exists == 'false' }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and Push Tag
        run: |
          git tag "v${{ needs.loading-files.outputs.version }}"
          git push --tags

      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Configure Maven Settings for GitHub Packages
        run: |
          mkdir -p $HOME/.m2
          cat <<EOF > $HOME/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build and Deploy to GitHub Packages
        run: |
          mvn clean install --settings $HOME/.m2/settings.xml
          mvn deploy --settings $HOME/.m2/settings.xml
