name: Push to Delivery

on:
  workflow_dispatch:

  push:
    paths:
      - 'src/**'
    branches:
      - delivery

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Validate Maven project
        run: mvn validate

      - name: Compile code
        run: mvn clean compile

      - name: Verify build
        run: mvn verify