name: 'Golang Testing'
description: 'Golang Testing Applications'
inputs:
  go_version:
    description: 'go version'
    required: true
    default: '^1.19'
  token_endpoint:
    description: 'Endpoint to generate accesstoken'
    required: true
  token_endpoint_x_api_key:
    description: 'XApiKey to generate accesstoken'
    required: true
  qodana_token:
    description: 'Qodana Token Applications'
    required: true
  git_ref:
    description: 'Qodana Token Applications'
    required: true
runs:
  using: composite
  steps:
  
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ inputs.qodana_token }}
