name: 'Code Testing'
description: 'Code Testing Applications'
inputs:
  qodana_token:
    description: 'Qodana Token Applications'
    required: true
  git_ref:
    description: 'Qodana Token Applications'
    required: true
runs:
  using: composite
  steps:
  
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ inputs.qodana_token }}
