name: 'Terraform Plan'
description: 'terraform plan commands'
inputs:
  aws_account_number:
    description: 'Account Number'
    required: true
    default: '067408622363'
  aws_role_name:
    description: 'Aws role with polices to deploy'
    required: true
    default: 'github-actions'
  aws_region: 
    description: 'Aws region'
    required: true
    default: 'us-east-1'
  token_endpoint:
    description: 'Endpoint to generate accesstoken'
    required: true
  token_endpoint_x_api_key:
    description: 'XApiKey to generate accesstoken'
    required: true
  terraform_state_file:
    description: 'State file Terraform'
    required: true
  terraform_bucket_name:
    description: 'Bucket Terraform'
    required: true
  terraform_env_file:
    description: 'Bucket Terraform'
    required: true
    default: .env
  check_changes:
    description: 'Get Code Plan'
    required: false
runs:
  using: composite
  steps:

  - name: configure aws credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::${{ inputs.aws_account_number }}:role/${{ inputs.aws_role_name }}
      role-session-name: ${{ inputs.aws_role_name }}
      aws-region: ${{ inputs.aws_region }}

  - name: Download Artifact
    uses: actions/download-artifact@v4
    with:
      name: terraform

  - name: Set permissions for Terraform providers
    shell: bash
    run: chmod -R +x .

  - name: Check Has Changes
    shell: bash
    id: terraform_plan
    run: |
      terraform plan -no-color -detailed-exitcode

  # - name: Set Output
  #   shell: bash
  #   run: |
  #     if [ ${{ steps.terraform_plan.outputs.has_change }} -eq 0 ]; then
  #       echo "No changes detected."
  #       echo "has_change=false" >> $GITHUB_OUTPUT
  #     else
  #       echo "Changes detected."
  #       echo "has_change=true" >> $GITHUB_OUTPUT
  #     fi

  # - name: Terraform Plan
  #   shell: bash
  #   run: |
  #     terraform plan -no-color | tee changes.txt

  # - name: Upload artifact
  #   uses: actions/upload-artifact@v4
  #   with:
  #     name: changes.txt
  #     path: changes.txt
  #     retention-days: 1
